### ISSUE TITLE
Nuget fails to install package for projects targetting .net 4.5

### ISSUE THREAD

**Issue by RoarkeRandall** [NickStrupat/PagedList.EntityFramework#1]
When running:
    Install-Package PagedList.EntityFramework
For a project targetting 4.5  it will fail:

Install failed. Rolling back...
Install-Package : Could not install package 'PagedList.EntityFramework 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any as
sembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
- Install-Package <<<<  PagedList.EntityFramework
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Works for 4.5.1 though.

**Comment by NickStrupat** [comment]
I've compiled the project for .NET 4.5 and updated the NuGet package with a build for .NET 4.5. Please update your package and enjoy!
