### ISSUE TITLE
Source not found error when stepping through code

### ISSUE THREAD

**Issue by bobinush** [NickStrupat/PagedList.EntityFramework#2]
Hello! First time making a issue on github so bare with me.
I'm stepping through my code in debugging mode (F11) and when I hit this block of code it gives me the error in the picture below.
Maybe you forgot to commit some file?

```
ProdukterViewModel ViewModel = new ProdukterViewModel
{
    Produkter = await items.ToPagedListAsync(pageNumber, pageSize),
    Kategori = kategori,
    SubKategori = subKategori,
    FargList = fargerArray,
    StorlekList = storlekarArray
};
```

http://i.imgur.com/otjb2tV.png

**Comment by NickStrupat** [comment]
That error is telling you that Visual Studio doesn't know where the source code is for `ToPagedListAsync(...)`. Your options are to use an integrated decompiler like ReSharper has, or wait for my to put the source code on SymbolSource.org (it is down at the moment, but I will try again tonight).
